Repository boostcampwm-2022/web34-moheyum, pull requests merged in 2022-11, with the labels that each got.

#40 feature #14 : 개발 환경 설정
  client/.eslintrc.json
  client/.gitignore
  client/.pnp.cjs
  client/.pnp.loader.mjs
  client/.prettierrc
  client/.vscode/extensions.json
  client/.vscode/settings.json
  client/.yarnrc.yml
  client/README.md
  client/next.config.js
  client/package.json
  client/pages/_app.tsx
  client/pages/api/hello.ts
  client/pages/index.tsx
  client/public/favicon.ico
  client/public/vercel.svg
  client/styles/Home.module.css
  client/styles/globals.css
  client/tsconfig.json
  client/yarn.lock
  server/.eslintrc.js
  server/.gitignore
  server/.prettierrc
  server/README.md
  server/nest-cli.json
  server/package.json
  server/prisma/schema.prisma
  server/src/auth/auth.controller.spec.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.spec.ts
  server/src/auth/auth.service.ts
  server/src/decorator/Cookie.decorator.ts
  server/src/decorator/index.ts
  server/src/main.ts
  server/src/modules/app.controller.spec.ts
  server/src/modules/app.controller.ts
  server/src/modules/app.module.ts
  server/src/modules/app.service.ts
  server/src/modules/auth/auth.controller.spec.ts
  server/src/modules/auth/auth.controller.ts
  server/src/modules/auth/auth.module.ts
  server/src/modules/auth/auth.service.spec.ts
  server/src/modules/auth/auth.service.ts
  server/src/modules/index.ts
  server/test/app.e2e-spec.ts
  server/test/jest-e2e.json
  server/tsconfig.base.json
  server/tsconfig.build.json
  server/tsconfig.json
  server/yarn.lock
Labels: frontend, backend, project management

#41 cicd: PR 전 빌드 테스트하는 CI 코드 추가
  .github/workflows/pr-test-be.yml
  .github/workflows/pr-test-fe.yml
Labels: project management

#45 feat(be): 유저와 무관한 단순 게시판 구현 #26
  server/package-lock.json
  server/package.json
  server/src/main.ts
  server/src/modules/app.module.ts
  server/src/modules/articles/article.repository.ts
  server/src/modules/articles/article.schema.ts
  server/src/modules/articles/articles.controller.ts
  server/src/modules/articles/articles.module.ts
  server/src/modules/articles/articles.service.ts
  server/src/modules/articles/dto/create-article.dto.ts
Labels: backend

#42 feature #32 : 회원가입 페이지 구현
  client/.eslintrc.json
  client/components/Login.tsx
  client/components/signup/SignupModal.tsx
  client/pages/index.tsx
  client/pages/login.tsx
  client/pages/signup.tsx
  client/public/ico_chveron_left.svg
Labels: feature, frontend

#43 feature #34 : 로그인 페이지 구현
  client/.gitignore
  client/components/Introduction.tsx
  client/components/login/Introduction.tsx
  client/components/login/Login.tsx
  client/pages/_app.tsx
  client/pages/_document.tsx
  client/pages/api/auth/signin.ts
  client/pages/api/hello.ts
  client/pages/index.tsx
  client/pages/login.tsx
  client/pages/main.tsx
  client/styles/color.ts
  client/styles/frame.ts
  client/styles/mixin.ts
Labels: feature, frontend

#48 feature #38 : 게시글 작성 페이지
  client/components/write/Editor.tsx
  client/pages/api/write.ts
  client/pages/write.tsx
Labels: feature, frontend

#53 test(fe): lighthouse ci 추가 #51
  .github/workflows/pr-test-fe.yml
  client/.lighthouserc.js
  client/.pnp.cjs
  client/.yarn/sdks/eslint/bin/eslint.js
  client/.yarn/sdks/prettier/index.js
  client/.yarn/sdks/typescript/bin/tsc
  client/.yarn/sdks/typescript/bin/tsserver
  client/README.md
  client/package.json
  client/yarn.lock
Labels: frontend, project management

#59 Feature/be/21 - login jwt with cookie
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.ts
  server/src/auth/dto/user-create-dto.ts
  server/src/auth/strategies/jwt.strategy.ts
  server/src/auth/strategies/refreshToken.strategy.ts
  server/src/common/config/jwtConfig.ts
  server/src/common/config/redisConfig.ts
  server/src/common/database/database.module.ts
  server/src/common/database/user.repository.ts
  server/src/common/database/user.schema.ts
  server/src/common/decorator/cookie.decorator.ts
  server/src/common/decorator/get-jwt-data.decorator.ts
  server/src/common/guard/jwt-auth.guard.ts
  server/src/common/guard/jwt-refresh.guard.ts
  server/src/common/middleware/logger.ts
  server/src/main.ts
  server/src/post/post.controller.ts
  server/src/post/post.module.ts
  server/src/redis/redis.module.ts
  server/src/redis/redis.service.ts
Labels: backend, user feature

#58 Feature/fe/57 프론트엔드 구조 정리
  client/.env.template
  client/.gitignore
  client/.prettierignore
  client/.vscode/sftp.json
  client/components/Login/Introduction/index.style.ts
  client/components/Login/Introduction/index.tsx
  client/components/Login/Login/index.style.ts
  client/components/Login/Login/index.tsx
  client/components/Main/Articlecard/index.style.ts
  client/components/Main/Articlecard/index.tsx
  client/components/Main/Mainsection/index.style.ts
  client/components/Main/Mainsection/index.tsx
  client/components/Main/SideBar/Menu/index.style.ts
  client/components/Main/SideBar/Menu/index.tsx
  client/components/Main/SideBar/Title/index.style.ts
  client/components/Main/SideBar/Title/index.tsx
  client/components/Main/SideBar/index.style.ts
  client/components/Main/SideBar/index.tsx
  client/components/Signup/index.style.ts
  client/components/Signup/index.tsx
  client/components/Write/index.style.ts
  client/components/Write/index.tsx
  client/components/login/Introduction.tsx
  client/components/main/MainSection.tsx
  client/components/main/SideBar/Title.tsx
  client/components/write/Editor.tsx
  client/next.config.js
  client/pages/_app.tsx
  client/pages/_document.tsx
  client/pages/announce.tsx
  client/pages/index.tsx
  client/pages/login.tsx
  client/pages/myAccount.tsx
  client/pages/search.tsx
  client/pages/signup.tsx
  client/pages/write.tsx
  client/styles/global.css
  client/styles/reset.css
  client/utils/http.ts
Labels: enhancement, frontend

#85 Feature/be/69 signup email
  server/.yarn/plugins/@yarnpkg/plugin-typescript.cjs
  server/.yarn/releases/yarn-3.2.4.cjs
  server/.yarn/releases/yarn-3.3.0.cjs
  server/.yarn/sdks/typescript/package.json
  server/.yarnrc.yml
  server/package.json
  server/src/auth/auth.controller.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.ts
  server/src/auth/dto/email-check-dto.ts
  server/src/auth/dto/email-request-dto.ts
  server/src/auth/strategies/jwt.strategy.ts
  server/src/common/guard/jwt-refresh.guard.ts
  server/src/post/post.controller.ts
  server/yarn.lock
Labels: feature, backend

#88 Feature/be/83 user info
  server/.yarn/releases/yarn-3.2.4.cjs
  server/.yarn/sdks/eslint/bin/eslint.js
  server/.yarn/sdks/prettier/index.js
  server/.yarn/sdks/typescript/bin/tsc
  server/.yarn/sdks/typescript/bin/tsserver
  server/.yarnrc.yml
  server/src/app.module.ts
  server/src/auth/auth.controller.ts
  server/src/auth/auth.service.ts
  server/src/auth/dto/user-create-dto.ts
  server/src/common/database/user.repository.ts
  server/src/common/database/user.schema.ts
  server/src/user/dto/user-Update-dto.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
  server/tsconfig.json
  server/yarn.lock
Labels: feature, backend

#84 Refactor/fe/81 Week 2 병합 작업
  client/atom/index.ts
  client/components/Login/Login/index.tsx
  client/components/Main/Mainsection/index.tsx
  client/components/Main/SideBar/Title/index.tsx
  client/components/Signup/index.tsx
  client/components/Write/index.tsx
  client/middleware.ts
  client/pages/_document.tsx
  client/pages/index.tsx
  client/utils/http.ts
  server/src/post/post.controller.ts
Labels: enhancement, frontend, backend

#92 Feature/be/83 user info
  server/src/auth/dto/user-create-dto.ts
  server/src/common/database/user.schema.ts
  server/src/user/dto/user-Update-dto.ts
  server/src/user/user.service.ts
Labels: bug, backend

#93 Feature/fe/34 인증 절차를 미들웨어에서 컴포넌트로
  client/components/AuthGuard.tsx
  client/components/Login/Login/index.tsx
  client/middleware.ts
  client/pages/announce.tsx
  client/pages/index.tsx
  client/pages/myAccount.tsx
  client/pages/search.tsx
  client/pages/write.tsx
Labels: frontend

#89 Feature/fe/35 게시글 읽기 페이지
  client/.eslintrc.json
  client/components/Main/Articlecard/index.tsx
  client/components/Main/Mainsection/index.tsx
  client/components/ReadPost/index.style.ts
  client/components/ReadPost/index.tsx
  client/pages/post/[pid].tsx
  client/styles/global.css
  client/styles/reset.css
  server/src/post/post.controller.ts
Labels: feature, frontend

#98 Feature/be/83 user info
  server/src/common/database/follow.repository.ts
  server/src/common/database/post.repository.ts
  server/src/common/database/user.repository.ts
  server/src/common/database/user.schema.ts
  server/src/follow/follow.controller.ts
  server/src/follow/follow.service.ts
  server/src/post/post.controller.ts
  server/src/post/post.service.ts
  server/src/user/dto/user-profile-dto.ts
  server/src/user/user.controller.ts
  server/src/user/user.service.ts
Labels: feature, backend

#104 fix(be): follow 신청, 취소 예외처리 #83
  server/src/follow/follow.service.ts
Labels: bug, backend

#105 fix(be): 팔로우 팔로잉 리스트 api 수정 #77
  server/src/follow/follow.controller.ts
  server/src/follow/follow.service.ts
Labels: enhancement, backend

#106 feat(BE): guard 추가 #83
  server/src/common/decorator/user-auth.decorator.ts
  server/src/common/guard/post.guard.ts
  server/src/common/guard/update-user.guard.ts
  server/src/post/post.controller.ts
  server/src/user/user.controller.ts
Labels: feature, backend

#109 fix(BE): follow, unfollow 없는 id, 출력 result 수정 #77
  server/src/follow/follow.module.ts
  server/src/follow/follow.service.ts
Labels: backend

#108 Feature/fe/62 63 72 profile and follow
  client/atom/index.ts
  client/components/AuthGuard.tsx
  client/components/Follow/FollowMember/index.style.ts
  client/components/Follow/FollowMember/index.tsx
  client/components/Follow/Follower.tsx
  client/components/Follow/Following.tsx
  client/components/Follow/index.style.ts
  client/components/Main/Articlecard/index.style.ts
  client/components/Main/Articlecard/index.tsx
  client/components/Main/Mainsection/index.tsx
  client/components/Main/SideBar/Menu/index.style.ts
  client/components/Main/SideBar/Menu/index.tsx
  client/components/Main/SideBar/index.tsx
  client/components/MyAccount/index.style.ts
  client/components/MyAccount/index.tsx
  client/components/ReadPost/index.style.ts
  client/components/ReadPost/index.tsx
  client/components/User/PostList/index.style.ts
  client/components/User/PostList/index.tsx
  client/components/User/Profile/ProfileCounter/index.style.ts
  client/components/User/Profile/ProfileCounter/index.tsx
  client/components/User/Profile/index.style.ts
  client/components/User/Profile/index.tsx
  client/components/User/index.style.ts
  client/components/User/index.tsx
  client/pages/index.tsx
  client/pages/myAccount.tsx
  client/pages/post/[pid].tsx
  client/pages/user/[userid].tsx
  client/pages/user/[userid]/follower.tsx
  client/pages/user/[userid]/following.tsx
  client/public/default-profile.png
  client/types/Post.ts
  client/utils/http.ts
  client/utils/paginator.ts
Labels: frontend

#141 Feature/fe/129 form data validation
  .gitignore
  client/.pnp.cjs
  client/components/Follow/Follower.tsx
  client/components/Follow/Following.tsx
  client/components/Main/SideBar/index.tsx
  client/components/ProfileEdit/index.style.ts
  client/components/ProfileEdit/index.tsx
  client/components/Signup/index.style.ts
  client/components/Signup/index.tsx
  client/components/User/Profile/ProfileCounter/index.tsx
  client/components/User/Profile/index.style.ts
  client/components/User/Profile/index.tsx
  client/package.json
  client/pages/[userid].tsx
  client/pages/[userid]/follower.tsx
  client/pages/[userid]/following.tsx
  client/pages/[userid]/profileEdit.tsx
  client/pages/myAccount.tsx
  client/yarn.lock
Labels: feature, frontend

#145 Feature/fe/126 UI refactor
  client/components/Follow/Follower.tsx
  client/components/Follow/Following.tsx
  client/components/Follow/index.style.ts
  client/components/Login/Introduction/index.style.ts
  client/components/Login/Introduction/index.tsx
  client/components/Login/Login/index.style.ts
  client/components/Login/Login/index.tsx
  client/components/Main/Mainsection/index.tsx
  client/components/Main/SideBar/Menu/index.style.ts
  client/components/Main/SideBar/Menu/index.tsx
  client/components/Main/SideBar/Title/index.style.ts
  client/components/Main/SideBar/Title/index.tsx
  client/components/Main/SideBar/index.style.ts
  client/components/ProfileEdit/index.style.ts
  client/components/ProfileEdit/index.tsx
  client/components/ReadPost/index.style.ts
  client/components/ReadPost/index.tsx
  client/components/User/Profile/index.style.ts
  client/components/User/index.style.ts
  client/components/Write/index.style.ts
  client/components/Write/index.tsx
  client/pages/_app.tsx
  client/styles/common.ts
  client/styles/frame.ts
  client/styles/theme.ts
Labels: enhancement, feature

#143 Feature/be/62 profile avatar upload
  server/src/common/database/user.repository.ts
  server/src/user/dto/user-Update-dto.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
Labels: backend

#142 Feature/be/132 comments 댓글 기능 구현
  server/src/common/database/post.repository.ts
  server/src/common/database/post.schema.ts
  server/src/post/dto/create-post.dto.ts
  server/src/post/post.controller.ts
  server/src/post/post.service.ts
Labels: backend

#148 fix(fe): 회원가입 url과 같은 아이디 validate #147
  client/components/ProfileEdit/index.tsx
  client/components/Signup/index.tsx
  client/utils/getByteLength.ts
Labels: enhancement, frontend

#150 feat(BE): 멘션 리스트 api 구현 #144
  server/src/common/database/follow.repository.ts
  server/src/user/user.controller.ts
  server/src/user/user.module.ts
  server/src/user/user.service.ts
Labels: backend

#151 Feature/be/115 search
  server/src/common/database/post.repository.ts
  server/src/common/database/post.schema.ts
  server/src/common/database/user.repository.ts
  server/src/common/database/user.schema.ts
  server/src/post/post.controller.ts
  server/src/post/post.service.ts
  server/src/user/user.controller.ts
  server/src/user/user.service.ts
Labels: backend

#154 Feature/fe/147 signup validate
  client/.pnp.cjs
  client/components/Follow/index.style.ts
  client/components/Main/Articlecard/index.style.ts
  client/components/Main/Mainsection/index.style.ts
  client/components/Main/Mainsection/index.tsx
  client/components/ProfileEdit/index.style.ts
  client/components/ReadPost/Comment/index.tsx
  client/components/ReadPost/ParentPost/index.style.ts
  client/components/ReadPost/ParentPost/index.tsx
  client/components/ReadPost/UserProfile/ProfileImg/index.tsx
  client/components/ReadPost/UserProfile/index.style.ts
  client/components/ReadPost/UserProfile/index.tsx
  client/components/ReadPost/index.style.ts
  client/components/ReadPost/index.tsx
  client/components/User/PostList/index.tsx
  client/components/User/Profile/index.tsx
  client/components/User/index.style.ts
  client/components/User/index.tsx
  client/components/Write/Editor/index.style.ts
  client/components/Write/Editor/index.tsx
  client/components/Write/index.tsx
  client/next.config.js
  client/package.json
  client/pages/[userid].tsx
  client/pages/_app.tsx
  client/pages/login.tsx
  client/pages/post/[pid].tsx
  client/pages/post/[pid]/comment.tsx
  client/pages/signup.tsx
  client/pages/write.tsx
  client/styles/color.ts
  client/styles/common.ts
  client/styles/frame.ts
  client/styles/mixin.ts
  client/styles/theme.ts
  client/types/Post.ts
  client/types/Theme.ts
  client/yarn.lock
Labels: feature, frontend

#158 Feature/fe/121 post page
  client/components/ReadPost/Comment/index.style.ts
  client/components/ReadPost/Comment/index.tsx
  client/components/ReadPost/UserProfile/ProfileImg/index.tsx
  client/components/ReadPost/UserProfile/index.style.ts
  client/components/ReadPost/index.style.ts
  client/components/ReadPost/index.tsx
Labels: enhancement, frontend

#162 Feature/161 matching URL 수정 작업
  client/components/Signup/index.tsx
  server/src/auth/dto/user-create.dto.ts
  server/src/follow/follow.service.ts
Labels: frontend, backend

#164 Feature/fe/116 markdown image
  client/components/Main/Articlecard/index.style.ts
  client/components/ProfileEdit/index.tsx
  client/components/User/index.style.ts
  client/components/Write/Editor/index.tsx
Labels: feature, frontend
