Repository boostcampwm-2022/web34-moheyum, pull requests merged in 2022-12, with the labels that each got.

#171 Feature/fe/124 검색 페이지 구현
  client/components/Follow/Follower.tsx
  client/components/Follow/Following.tsx
  client/components/Main/Mainsection/index.style.ts
  client/components/Notification/index.tsx
  client/components/ProfileEdit/index.tsx
  client/components/ReadParentPost/index.tsx
  client/components/ReadPost/index.style.ts
  client/components/ReadPost/index.tsx
  client/components/Search/PostResult/index.tsx
  client/components/Search/UserResult/index.tsx
  client/components/Search/index.tsx
  client/components/Write/Editor/index.style.ts
  client/components/Write/index.tsx
  client/pages/search.tsx
  client/styles/common.ts
  client/styles/mixin.ts
  client/utils/paginator.ts
Labels: feature, frontend

#173 Feature/fe/117 mention
  client/components/Write/Editor/UserDropDown/index.style.ts
  client/components/Write/Editor/UserDropDown/index.tsx
  client/components/Write/Editor/index.tsx
  client/styles/theme.ts
Labels: feature, frontend

#176 Feature/fe/175 delete post
  client/components/Main/Articlecard/UserProfile/index.tsx
  client/components/ProfileImg/index.tsx
  client/components/ReadParentPost/index.tsx
  client/components/ReadPost/ParentPost/index.tsx
  client/components/ReadPost/UserProfile/index.tsx
  client/components/ReadPost/index.style.ts
  client/components/ReadPost/index.tsx
  client/components/Write/Editor/index.tsx
  client/utils/http.ts
Labels: feature, frontend

#195 Feature/be/183 sse - 프론트엔드랑 같이 작업했습니다
  client/.pnp.cjs
  client/atom/index.ts
  client/components/Main/Mainsection/index.style.ts
  client/components/Main/SideBar/Menu/index.style.ts
  client/components/Main/SideBar/Menu/index.tsx
  client/components/Main/SideBar/index.tsx
  client/components/Notification/index.style.ts
  client/components/Notification/index.tsx
  client/package-lock.json
  client/package.json
  client/yarn.lock
  server/.gitignore
  server/src/alarm/event.contoller.ts
  server/src/alarm/event.module.ts
  server/src/alarm/event.service.ts
  server/src/app.module.ts
  server/src/follow/follow.module.ts
  server/src/follow/follow.service.ts
  server/src/notification/notification.controller.ts
  server/src/post/post.module.ts
  server/src/post/post.service.ts
Labels: feature, frontend, backend

#197 Feature/fe/179 my account
  client/components/Main/SideBar/SideBarDropdown.tsx
  client/components/MyAccount/index.style.ts
  client/components/MyAccount/index.tsx
  client/pages/myAccount.tsx
  client/utils/http.ts
Labels: feature, frontend

#199 feat(FE): 토스트 메시지 구현
  client/atom/index.ts
  client/components/AuthGuard.tsx
  client/components/Main/SideBar/index.tsx
  client/components/Notification/index.tsx
  client/components/Toast/ToastMessage.tsx
  client/components/Toast/index.tsx
  client/pages/_app.tsx
  client/types/Toast.ts
Labels: feature, frontend

#202 Feature/fe/201 ux fix
  client/components/Follow/Follower.tsx
  client/components/Follow/Following.tsx
  client/components/Login/Introduction/index.style.ts
  client/components/Login/Introduction/index.tsx
  client/components/Login/Login/index.style.ts
  client/components/MainSection/index.style.ts
  client/components/MainSection/index.tsx
  client/components/Notification/index.tsx
  client/components/ReadPost/index.tsx
  client/components/Search/PostResult/index.tsx
  client/components/Search/UserResult/index.tsx
  client/components/Search/index.style.ts
  client/components/Search/index.tsx
  client/components/SideBar/Title/index.style.ts
  client/components/SideBar/Title/index.tsx
  client/components/User/PostList/index.tsx
  client/components/UserProfile/ProfileImg/index.tsx
  client/components/Write/Editor/index.style.ts
  client/components/Write/Editor/index.tsx
  client/components/Write/index.tsx
  client/hooks/usePaginator.ts
  client/pages/_app.tsx
  client/pages/_document.tsx
  client/public/logo_purple.svg
  client/public/logo_white.svg
  client/public/moheyum.svg
  client/public/moheyum_white.svg
  client/styles/common.ts
  client/styles/mixin.ts
Labels: enhancement, frontend

#207 feat(CICD): docker, compose, swarm, CD #169 #190
  .github/workflows/deploy-dev-be.yml
  .github/workflows/deploy-dev-fe.yml
  .github/workflows/deploy-dev-nginx.yml
  .github/workflows/pr-test-fe.yml
  .gitignore
  client/.dockerignore
  client/Dockerfile
  client/package.json
  client/stack-dev.yml
  docker-compose.yml
  mongodb/Dockerfile
  nginx/Dockerfile
  nginx/conf.d/moheyum-dev.conf
  nginx/conf.d/moheyum-local.conf
  nginx/nginx.conf
  nginx/stack-dev.yml
  package.json
  server/.dockerignore
  server/Dockerfile
  server/src/common/database/post.schema.ts
  server/stack-dev.yml
Labels: project management

#205 Feature/fe/204 inquiry
  client/components/CommentPost/index.tsx
  client/components/Follow/FollowMember/index.tsx
  client/components/Idinquiry/index.style.ts
  client/components/Idinquiry/index.tsx
  client/components/Login/Introduction/index.tsx
  client/components/MainSection/Articlecard/index.tsx
  client/components/Notification/index.tsx
  client/components/ProfileEdit/index.style.ts
  client/components/ProfileEdit/index.tsx
  client/components/Pwinquiry/index.style.ts
  client/components/Pwinquiry/index.tsx
  client/components/ReadPost/MainPost/index.style.ts
  client/components/ReadPost/MainPost/index.tsx
  client/components/ReadPost/index.tsx
  client/components/SideBar/Menu/index.style.ts
  client/components/SideBar/Menu/index.tsx
  client/components/SideBar/Title/index.style.ts
  client/components/SideBar/Title/index.tsx
  client/components/Signup/index.style.ts
  client/components/Signup/index.tsx
  client/components/User/Profile/index.style.ts
  client/components/User/Profile/index.tsx
  client/components/UserProfile/ProfileImg/index.tsx
  client/components/Write/Editor/index.tsx
  client/pages/_app.tsx
  client/pages/idinquiry.tsx
  client/pages/pwinquiry.tsx
  client/public/menu.svg
  client/public/moheyum.svg
  client/styles/frame.ts
  client/styles/mixin.ts
Labels: feature, frontend

#203 Feature/fe/201 ux fix
  client/public/moheyum.svg
Labels: enhancement, frontend

#209 feat(BE): skip추가, 로깅 한 파일내 작성
  server/src/common/utils/winston.util.ts
Labels: backend

#211 Feature/fe/210 past action
  client/components/Write/Editor/index.tsx
Labels: bug, frontend

#212 Refactor/206 markdown
  client/components/MainSection/Articlecard/index.style.ts
  client/components/MainSection/Articlecard/index.tsx
  client/components/MainSection/index.tsx
  client/components/ReadPost/Comment/index.tsx
  client/components/ReadPost/MainPost/index.tsx
  client/components/ReadPost/ParentPost/index.tsx
  client/components/Search/PostResult/index.tsx
  client/components/Search/index.tsx
  client/components/SideBar/Menu/index.style.ts
  client/components/SideBar/index.tsx
  client/components/User/PostList/index.tsx
  client/components/Write/Editor/index.tsx
  client/public/announce.svg
  client/public/home.svg
  client/public/ico_comment.svg
  client/public/ico_home.svg
  client/public/ico_notification.svg
  client/public/ico_search.svg
  client/public/ico_setting.svg
  client/public/moheyum.svg
  client/public/profile_img.svg
  client/public/search.svg
  client/public/setting.svg
  client/styles/common.ts
  client/utils/markdown/index.ts
  client/utils/markdown/rules.ts
Labels: enhancement, frontend

#215 Feature/fe/186 sse
  client/components/Login/Login/index.tsx
  client/components/Notification/index.tsx
  client/styles/frame.ts
Labels: enhancement, frontend

#216 Feature/fe/118 notification
  client/components/Notification/NotificationCard/index.tsx
  client/components/Notification/index.style.ts
  client/components/Notification/index.tsx
  client/components/ReadPost/MainPost/index.tsx
Labels: feature, frontend

#218 Feature/fe/217 editor enhancement
  client/components/ProfileEdit/index.style.ts
  client/components/Search/index.style.ts
  client/components/Search/index.tsx
  client/components/SideBar/index.style.ts
  client/components/SideBar/index.tsx
  client/components/Signup/index.tsx
  client/components/Toast/ToastMessage.tsx
  client/components/Write/Editor/UserDropDown/index.tsx
  client/components/Write/Editor/index.tsx
  client/hooks/useToast.ts
  client/styles/common.ts
  client/styles/mixin.ts
  client/utils/markdown/index.ts
  client/utils/markdown/rules.ts
Labels: enhancement, feature, frontend

#219 Feature/fe/noti error
  client/components/NotFound/index.tsx
  client/components/SideBar/Title/index.style.ts
  client/components/SideBar/Title/index.tsx
  client/pages/post/[pid].tsx
Labels: bug, frontend

#227 Feature/fe/226 loading UI
  client/components/Follow/Follower.tsx
  client/components/Follow/Following.tsx
  client/components/Follow/index.style.ts
  client/components/MainSection/index.style.ts
  client/components/MainSection/index.tsx
  client/components/Notification/index.style.ts
  client/components/Notification/index.tsx
  client/components/ReadPost/index.style.ts
  client/components/ReadPost/index.tsx
  client/components/Search/PostResult/index.tsx
  client/components/Search/UserResult/index.tsx
  client/components/User/PostList/index.style.ts
  client/components/User/PostList/index.tsx
  client/hooks/usePaginator.ts
  client/pages/_app.tsx
  client/styles/common.ts
Labels: bug, enhancement, frontend

#225 Feature/be/184 helmet
  server/package.json
  server/src/app.module.ts
  server/src/auth/auth.controller.ts
  server/src/common/config/registerConfig.ts
  server/src/main.ts
  server/yarn.lock
Labels: backend

#228 Refactor/fe/minor fixes
  client/components/CommentPost/index.tsx
  client/components/ReadPost/ParentPost/index.style.ts
  client/components/ReadPost/ParentPost/index.tsx
  client/components/ReadPost/index.tsx
  client/components/UserProfile/ProfileImg/index.tsx
  client/components/Write/Editor/index.style.ts
  client/components/Write/Editor/index.tsx
  client/utils/markdown/rules.ts
Labels: bug, enhancement, frontend

#231 Fix/fe/minor fix
  client/components/MainSection/index.style.ts
  client/components/MainSection/index.tsx
  client/components/ReadPost/ParentPost/index.style.ts
  client/components/ReadPost/ParentPost/index.tsx
  client/components/ReadPost/index.style.ts
  client/utils/markdown/rules.ts
Labels: bug, frontend

#234 Refactor/be/mail
  server/package.json
  server/src/app.module.ts
  server/src/auth/auth.module.ts
  server/src/auth/auth.service.ts
  server/src/common/config/mailConfig.ts
  server/src/common/constants/mail.constants.ts
  server/src/mail/dto/send-email.dto.ts
  server/src/mail/mail.interface.ts
  server/src/mail/mail.module.ts
  server/src/mail/mail.service.ts
  server/yarn.lock
Labels: backend

#238 fix(FE): opengraph가 제대로 적용되지 않음
  client/pages/_document.tsx
  client/public/og_image.png
Labels: bug, frontend
